# Generated by Django 5.2 on 2025-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
