# Generated by Django 5.2 on 2025-08-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0002_problem_submission_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True, help_text='Initial code template for users'),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_test_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Correct solution code')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether the solution is shown to users')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='LearnApp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(help_text='Input data for the test case')),
                ('expected_output', models.TextField(help_text='Expected output for the test case')),
                ('is_public', models.BooleanField(default=False, help_text='Whether the test case is shown to users')),
                ('order', models.IntegerField(default=0, help_text='Order of test case execution')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='LearnApp.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
