# Generated by Django 5.2 on 2025-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0003_problem_template_code_submission_test_cases_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='input_code',
            field=models.TextField(default=None, help_text='Input code'),
            preserve_default=False,
        ),
    ]
