# Generated by Django 5.2 on 2025-08-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0004_solution_input_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='input_code',
        ),
    ]
