# Generated by Django 5.2 on 2025-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0005_remove_solution_input_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the test case', max_length=200),
        ),
    ]
